fruits=["apply","banana","cherry"]
print(fruits[2])
#เปลี่ยนคำในlist
fruits[1]="blackcurrant"
print(fruits)
fruits=[1:3]=["banana","kiwi","melon"]
print(fruits)
fruits[1:3]="blackcurrant"
print(fruits)
#เพิ่มคำในlist
fruits.append("kiwi")
print(fruits)
fruits.insert(1,"banana")
print(fruits)
tropical=["mango","pineapple","papaya"]
fruits.extend(tropical)
print(fruits)
#ลบคำในlist
fruits.remove('pineapple')
print(fruits)
fruits.pop(3)
print(fruits)
#del fruits: ลบตัวแปลlistทิ้งไปจากระบบ
#เรียงคำในlist
fruits.sort
print(fruits)
fruits.sort(reversed=True)
print(fruits)
vege=["carrot","potato","cucamber"]
all=fruits+vege
print(all)
#นางสาวขวัญหทัย สนิทกลาง ม.6/11 เลขที่35
